---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-bench-pvc
  namespace: prombench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: general
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: grafana
  name: grafana-bench
  namespace: prombench
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      # tolerations:
      # - effect: NoSchedule
      #   key: dedicated
      #   value: master
      # - effect: NoSchedule
      #   key: CriticalAddonsOnly
      #   value: "True"
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:10.4.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: web
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 600
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            # limits:
            #   cpu: "2000m"
            #   memory: "4096Mi"
            requests:
              cpu: "250m"
              memory: "768Mi"
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-bench-pv
      volumes:
        - name: grafana-bench-pv
          persistentVolumeClaim:
            claimName: grafana-bench-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prombench
spec:
  ports:
  - name: web
    port: 3000
    targetPort: web
  selector:
    app.kubernetes.io/name: grafana
  type: NodePort
