---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: generate-timeseries
  name: generate-timeseries
  namespace: prombench
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: generate-timeseries
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generate-timeseries
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: generate-timeseries
            weight: 1
      nodeSelector:
        kubernetes.io/os: linux
      # tolerations:
      # - effect: NoSchedule
      #   key: dedicated
      #   value: master
      # - effect: NoSchedule
      #   key: CriticalAddonsOnly
      #   value: "True"
      containers:
        - name: generate-timeseries
          image: quay.io/hoperays/prombench:latest
          imagePullPolicy: Always
          args:
            - --timeseries=10000
          ports:
            - containerPort: 12345
              name: metrics
          resources:
            # limits:
            #   cpu: "1000m"
            #   memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    prometheus.io/used-by: bench
  name: generate-timeseries
  namespace: prombench
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: generate-timeseries
  namespaceSelector:
    matchNames:
      - prombench
  podMetricsEndpoints:
  - path: /metrics
    # interval: 30s
    # scrapeTimeout: 29s
    relabelings:
      - sourceLabels:
          - __meta_kubernetes_pod_container_port_number
        regex: "12345"
        action: keep
      - regex: __meta_kubernetes_pod_(node_name|host_ip)
        action: labelmap
      - targetLabel: job
        replacement: generate-timeseries
        action: replace
