---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus.io/used-by: bench
  name: bench.rules
  namespace: prombench
spec:
  groups:
  - name: prombench.rules
    rules:
    - alert: 命名空间pod的容器实验数据５分钟内增长超过40
      expr: sort_desc(increase(example_timeseries_total[5m])) > 40
      for: 1m
      labels:
        purpose: bench
        severity: info
      annotations:
        summary: "命名空间 {{ $labels.namespace }} 下，pod {{ $labels.pod }} 的容器 {{ $labels.container }} 实验数据５分钟内增长超过40，当前为 {{ $value | humanize }}。"
        description: "命名空间 {{ $labels.namespace }} 下，pod {{ $labels.pod }} 的容器 {{ $labels.container }} 实验数据５分钟内增长超过40，持续1分钟告警。"
        solution: "压力测试触发的告警，请忽略。"
